# Generated by Django 5.2 on 2025-05-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='drive_wheel',
        ),
    ]
